### PR TITLE
Add relevance object replacing confusing HashMap data structure

### PR DESCRIPTION
**Pull request by tapishr**
Please check the action items covered in the PR - 

- [x] Build is running
- [ ] Eventing is functional and tested
- [ ] Unit or integration tests added and running
- [ ] Manual QA

### CODE REVIEW

**Comment by MuskanPaliwal** [comment]
Relevant users for this PR:

| Contributor Name/Alias  | Relevance |
| -------------- | --------------- |
| tapish303@gmail.com | 100.00% |


Auto assigning to all relevant reviewers

If you are a relevant reviewer, you can use the [Vibinex browser extension](https://chromewebstore.google.com/detail/vibinex-code-review/jafgelpkkkopeaefadkdjcmnicgpcncc) to see parts of the PR relevant to you
Relevance of the reviewer is calculated based on the git blame information of the PR. To know more, hit us up at contact@vibinex.com.

To change comment and auto-assign settings, go to [your Vibinex settings page.](https://vibinex.com/u)

**Comment by MuskanPaliwal** [comment]
Relevant users for this PR:

| Contributor Name/Alias  | Relevance |
| -------------- | --------------- |
| tapish303@gmail.com | 100.00% |


Auto assigning to all relevant reviewers

If you are a relevant reviewer, you can use the [Vibinex browser extension](https://chromewebstore.google.com/detail/vibinex-code-review/jafgelpkkkopeaefadkdjcmnicgpcncc) to see parts of the PR relevant to you
Relevance of the reviewer is calculated based on the git blame information of the PR. To know more, hit us up at contact@vibinex.com.

To change comment and auto-assign settings, go to [your Vibinex settings page.](https://vibinex.com/u)

**Comment by tapishr** [comment]
Name of Coverage should be something like RelevanceMatrix.

**Comment by tapishr** [comment]
> Name of Coverage should be something like RelevanceMatrix.

Named it "relevance", since that's what it basically is, a wrapper around the numerical relevance value and its git alias. @avikalpg - please re-review

**Review by avikalpg — DISMISSED** [review]
This looks good to me. But why not raise this PR directly on the `main` branch? @tapishr

**Comment by tapishr** [comment]
> This looks good to me. But why not raise this PR directly on the `main` branch? @tapishr


> This looks good to me. But why not raise this PR directly on the `main` branch? @tapishr

@avikalpg - I can't. This has changes affecting approval comment that will not work on main yet

**Comment by MuskanPaliwal** [comment]
Relevant users for this PR:

| Contributor Name/Alias  | Relevance |
| -------------- | --------------- |
| tapish303@gmail.com | 100.00% |


Auto assigning to all relevant reviewers

If you are a relevant reviewer, you can use the [Vibinex browser extension](https://chromewebstore.google.com/detail/vibinex-code-review/jafgelpkkkopeaefadkdjcmnicgpcncc) to see parts of the PR relevant to you
Relevance of the reviewer is calculated based on the git blame information of the PR. To know more, hit us up at contact@vibinex.com.

To change comment and auto-assign settings, go to [your Vibinex settings page.](https://vibinex.com/u)

**Comment by MuskanPaliwal** [comment]
Relevant users for this PR:

| Contributor Name/Alias  | Relevance |
| -------------- | --------------- |
| tapish303@gmail.com | 100.00% |


Auto assigning to all relevant reviewers

If you are a relevant reviewer, you can use the [Vibinex browser extension](https://chromewebstore.google.com/detail/vibinex-code-review/jafgelpkkkopeaefadkdjcmnicgpcncc) to see parts of the PR relevant to you
Relevance of the reviewer is calculated based on the git blame information of the PR. To know more, hit us up at contact@vibinex.com.

To change comment and auto-assign settings, go to [your Vibinex settings page.](https://vibinex.com/u)

**Pull request merged**
